### ISSUE TITLE
Usage with custom buttons.

### ISSUE THREAD

**Issue by MichalCz** [ranbuch/accessibility#1]
Hi,

You're doing a great work here. :)

I'm trying to use the library with some custom buttons. Would it be possible to add an option not to start the accessibility menu by default and just expose the methods? Or perhaps I just didn't find it in the documentation?

**Comment by ranbuch** [comment]
Hi @MichalCz, sorry for the late response.

While it's not possible to do so you can however just add this `css`:
```css
body ._access-icon {
    display: none;
}
```
and for executing the methods you can just click the buttons programmatically like so:
```javascript
document.querySelector('[data-access-action=decreaseText]').click();
```

Obviously that's a bit clunky so if you want I guess I can expose the methods and add an option to hide the menu by default.

Let me know if it is still relevant.

**Comment by ranbuch** [comment]
I've just realized I am exposing the methods under the `menuInterface` object on the constructor's return instance.

Example:
```javascript
var instance = new Accessibility();
instance.menuInterface..increaseText();
```

**Comment by MichalCz** [comment]
Thanks, I did solve it in some way back then - maybe it'd be worth to document this somewhere? :)

**Comment by ranbuch** [comment]
> Thanks, I did solve it in some way back then - maybe it'd be worth to document this somewhere? :)

Done
