### ISSUE TITLE
Hotkeys default enabled or disabled?

### ISSUE THREAD

**Issue by brianteeman** [ranbuch/accessibility#10]
The documentation at https://ranbuch.github.io/accessibility/ says that the default for a feature is enabled.

But when looking at the code to debug why "hotkeys" was not working I saw that it is set to default to disabled.

https://github.com/ranbuch/accessibility/blob/d9ebbcf45b1758e5df83f400075d7718b67d1608/src/main.js#L25

**Comment by SeFeX** [comment]
I just made a pull request with the changes in the documentation explaining the hotkeys module and activating it on the documentation page

**Comment by ranbuch** [comment]
Thank you @SeFeX 
@brianteeman it appears that I was incorrect, documentation is not fixed.
