### ISSUE TITLE
Font size does not work correctly for rem units, and ignores browser settings

### ISSUE THREAD

**Issue by Fedik** [ranbuch/accessibility#13]
While trying to use your scrip I found that approach that you use to manipulate the font size does not work even if the font size of the site is in a relative units (`rem` in my case).

If you know what is `rem` unit then you already may guess the reason of bug.

Instead of changing `<body>` font size, the script should manipulate with `document` font size (that is `<html>` element).
Please check section "Base font size and accessibility"
https://betterwebtype.com/articles/2019/06/16/5-keys-to-accessible-web-typography/

To do this without loosing users who use "old school" `body{font-size:12px}`, I would suggest next:
- on init, calculate `html` and `body` font sizes, and their difference
- then set `body` font size in `em` (calculated difference from `html`)
- set `html` font size in percent instead of pixels, this still will allow to users to use browser settings

Let say, `html` has font 16px (default for most browsers) and `body` 14px, the script need to set `body` font size 0.875em. And change `html` font size, when user click Bigger/Smaller, in `%` from existing font size.

btw, the demo page also ignores user font size from browser setting.

Additionally I would suggest to remove `textPixelMode: true` possibility, it just killing any site performance, especially big ones.

**Comment by ranbuch** [comment]
That's actually a very good idea @Fedik , thank you for the suggestion.
Version `3.0.9` now implements your approach as the default method for altering text size.

For legacy approach you can use `textEmlMode: false`.

Regarding `textPixelMode: true` you may be right but perhaps there are some cases we cannot predict in advance, you can never know how developers might write there code.

**Comment by Fedik** [comment]
thanks for doing it!
