### ISSUE TITLE
crash text to speech on chrome 93

### ISSUE THREAD

**Issue by ahmaddie1378** [ranbuch/accessibility#22]
while using google voices , google US English ,  google UK English male ,  google UK English female it reads some then crash only on google chrome and work well on others browsers and it even work well on chrome when i change default voice to microsoft zira voice

**Comment by ranbuch** [comment]
Hi @ahmaddie1378 sorry for the late response.

Does it still happens on Chrome 94? And on Chrome Canary?

Also, what language are you using for your site? You can try to use the `textToSpeechLang` attribute on the options.

Maybe you are translating the site with Chrome's built in google translate? Do you have a `lang` attribute on your `html` element?

**Comment by ranbuch** [comment]
Closing this for lack of response.
