### ISSUE TITLE
ability to resize the icon

### ISSUE THREAD

**Issue by edu-propdo** [ranbuch/accessibility#23]
Hi,
First of all thanks for this tool.
I was wondering is there is the possibility to change the icon size?
I could not find info about this on the documentation.
If currently it is not possible, will you be able to add this possibility?
Thanks

**Comment by ranbuch** [comment]
Hi @edu-propdo , sorry for the late response.

You can try to use the `icon.dimensions.width.size` on the `options` object.

Should work like this:

```javascript
var options = {
	icon: {
		dimensions: {
			width: {
				size: '100',
				units: 'px'
			},
			height: {
				size: '100',
				units: 'px'
			}
		}
	}
}

window.addEventListener('load', function () { new Accessibility(options); }, false);
```

BTW, you can always add your own CSS like this:

```html
<style>
        ._access-icon {
            width: 100px !important;
            height: 100px !important;
        }
</style>
```

Hope this helps.

**Comment by edu-propdo** [comment]
Hi Ran,
Thanks for your reply.
Yes, it helps.
