### ISSUE TITLE
screenreader not working with submit buttons

### ISSUE THREAD

**Issue by ereztaiar** [ranbuch/accessibility#25]
Hi,

There seams to be an issue with the screen reader preventing some events from being passed forward in forms
I am using a react, this isn't happen always.
Might be a state issue in components using hooks

**Comment by ranbuch** [comment]
When the user clicks on the "text to speech" option we are preventing all default click events behaviors in order to not trigger any other behavior except reading the text on click. This is intentional. If the user want's to do something else he should toggle the "text to speech" option off.
