### ISSUE TITLE
Invert colors filter breaks fixed positioned items on firefox

### ISSUE THREAD

**Issue by pabichw** [ranbuch/accessibility#26]
When Invert Colors options is toggled `filter: invert(1)` is added to html tag. Works good on Chrome, but there is a werid behaviour on Firefox where all fixed positioned elements suddenly lose this property going back to initial positioning. 
This can be well seen on accessibility menu itself (it jumps to very bottom of the page).

I assume it's a Firefox bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1226095

Is there a walkaround you would suggest to make it work?

**Comment by ranbuch** [comment]
Pretty sure this issue has been fixed.
