### ISSUE TITLE
Could not resolve '1em Material+Icons' as a font.

### ISSUE THREAD

**Issue by aagostini12** [ranbuch/accessibility#29]
Hello! I'm using this plugin in Vue + nuxt and it's giving me the following error:

Failed to execute 'check' on 'FontFaceSet': Could not resolve '1em Material+Icons' as a font.

Any solutions?

**Comment by brianteeman** [comment]
This is because of the incorrect change in the code in #27 

revert that change and it will work

**Comment by aagostini12** [comment]
Thank you!
