### ISSUE TITLE
#27 broke everything - please revert

### ISSUE THREAD

**Issue by brianteeman** [ranbuch/accessibility#31]
The change in #27 just broke the script for everyone. 

With this change you now get the following error

which results in
`Uncaught (in promise) DOMException: Failed to execute 'check' on 'FontFaceSet': Could not resolve '1em Material+Icons' as a font.`

### windows chrome
![image](https://user-images.githubusercontent.com/1296369/154086834-24bc54d1-1687-47a6-866a-31fbe6a095bf.png)

### mac safari monterey 15.1
![image](https://user-images.githubusercontent.com/1296369/154087394-c7346586-a4ed-40a4-8e96-617624153013.png)

If you revert that change then it works again

### windows chrome
![image](https://user-images.githubusercontent.com/1296369/154087724-00567c7f-5e37-4a59-9e64-eace1e211e3d.png)

### mac safari monterey 15.1
![image](https://user-images.githubusercontent.com/1296369/154087675-fa8b221c-afae-452e-ad2e-426f2624923b.png)

**Comment by ranbuch** [comment]
Fixed on version `3.0.16`
