### ISSUE TITLE
it loads fonts / icons

### ISSUE THREAD

**Issue by SorinSu** [ranbuch/accessibility#38]
hi,

it looks good, but unfortunately it loads external fonts which nowadays may cause massive problems because of GDPR.

Any plans to change this?

**Comment by ranbuch** [comment]
Hi @SorinSu ,

You can initiate the instance like this:

```javascript
new Accessibility({ icon: { useEmojis: true } });
```

Hope this helps.

**Comment by fabiojust** [comment]
Hi @ranbuch , great work. I'm using your plugin in Joomla; for the same problem of @SorinSu i want to charge Material Icons locally. It seams to be possible but the plugins open the online source googleapis anyway. Can you help me?

**Comment by ranbuch** [comment]
Thanks @fabiojust , we need to allow loading the material icons font from other locations as well as the default [google fonts](https://fonts.googleapis.com/icon?family=Material+Icons).

Reopening this issue, don't know when I'll be able to implement this behavior.

**Comment by mustafauysal** [comment]
I've opened a PR that replaces Google Fonts with Bunny Fonts. It might be easier to use since it's a drop-in replacement and there's not much to do. 

Also, +1 for allowing fonts to be loaded from other locations.

**Comment by ranbuch** [comment]
@SorinSu @fabiojust Please see this [issue](https://github.com/ranbuch/accessibility/pull/59) that includes a fix for the problem.
