### ISSUE TITLE
Can not find window

### ISSUE THREAD

**Issue by It-SuperDev** [ranbuch/accessibility#39]
Hello, Ran Buchnik.
I used accessibility module and feeling it is very good.
But I found an issue. When I use it in **React** it worked perfect.
Nowadays, I built a project using **Frontity**.
When run project, Accessibility is caused an issue that can't find window object.
So I replaced the last code of a JS file to solve this.

node_modules/accessibility/dist/accessibility.js.

```
if (typeof window !== 'undefined') {
  window.Accessibility = _main["default"];
}
```

I hope you fix this issue.

Regards.

**Comment by ranbuch** [comment]
Thanks for letting me know @It-SuperDev ,
Could this work?
`self.Accessibility = _main["default"];`

**Comment by ranbuch** [comment]
Changed window to self, please let me know if that's fixing your issue.

**Comment by It-SuperDev** [comment]
I checked with `self`.
But I got another issue like `ReferenceError: regeneratorRuntime is not defined` in new version.
Also I think this module works well on other fraimeworks but only donesn't work on Frontity.
I don't know well about frontity but we can't get window object.
So I suggest you fix this problem with exception handling as I already pointed out on above.
There is no error in the module.

Thank you.

**Comment by ranbuch** [comment]
I don't understand how you are not getting `self` or `window`. Is this not running on the browser? Anyway, please check `4.5.2` and let me know.

**Comment by It-SuperDev** [comment]
Thank you for your trying.
I checked the new version. But I think you changed some from ^4.4.1 version.
Now I get `ReferenceError: regeneratorRuntime is not defined` error.
As I said the module works well and my issue cames from Frontity framework.
So, I would like you to change the `node_modules/accessibility/dist/accessibility.js` file of version ^4.4.1 to check only the `window` object.

Best regards.

**Comment by ranbuch** [comment]
Here is the current [file](https://github.com/ranbuch/accessibility/blob/master/dist/accessibility.js#L129). Please have a look on the last line of code:

![image](https://user-images.githubusercontent.com/3777546/199499610-ed6fc41f-7f52-459b-8f2b-756aaa37c160.png)

**Comment by ranbuch** [comment]
Perhaps it has something to do with your project? Maybe it doesn't accept ES2015 or something like that?
Also, [this post](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined) might be relevant. I do use `async` `await` syntax.

**Comment by It-SuperDev** [comment]
Yes, it is frontity framework issue.
I hope you check your module on frontity.

**Comment by ranbuch** [comment]
Is there a quick way to do it? Some project that I can clone, install the module and run it? I've never developed on WordPress or React.

**Comment by ranbuch** [comment]
@It-SuperDev could you try to reoroduce [here](https://codesandbox.io/s/github/frontity/frontity-template)?

**Comment by It-SuperDev** [comment]
So it is working or not?

**Comment by ranbuch** [comment]
I have no idea, was hoping you could reproduce and send me a link.

**Comment by It-SuperDev** [comment]
```
if (typeof window !== 'undefined') {
  window.Accessibility = _main["default"];
}
```

This is the idea.
Please make version same as 4.4.1 and add above code.
Then it will work perfectly.

**Comment by ranbuch** [comment]
Is [that](https://github.com/ranbuch/accessibility/blob/master/dist/accessibility.js#L129) okay?

**Comment by It-SuperDev** [comment]
difficult to solve
