### ISSUE TITLE
error - missing textToSpeech and speechToText on resetAll action

### ISSUE THREAD

**Issue by FedyukRimon** [ranbuch/accessibility#49]
Hello,

If `textToSpeech` or `speechToText` features are not loaded in the menu interface, due to the lack of browser support or unsupported languages, the following error occurs on the `resetAll` action:

<img width="1266" alt="Screen Shot 2022-12-16 at 7 46 56 PM" src="https://user-images.githubusercontent.com/42584893/208158100-331db253-4aea-4bbf-aaa7-00645859d281.png">

<img width="792" alt="Screen Shot 2022-12-16 at 7 48 23 PM" src="https://user-images.githubusercontent.com/42584893/208158672-c1056c9a-561c-4101-bfd4-41ce2ce28118.png">

I try to solve the error, see PR: [https://github.com/ranbuch/accessibility/pull/48](url)
(Let me know if you think we should solve it differently - happy to fix it).

**Comment by ranbuch** [comment]
Thanks you @FedyukRimon ! I believe this would fix it but I think we should do it a bit differently. The `resetAll()` function doesn't check any other feature for support or activity state. I think the `textToSpeech(destroy: boolean)` under the `menu-interface.ts` file should be smart about it and check if `tSpeechList` is falsy or not. If it is, I think it should return:
```javascript
let tSpeechList = document.querySelector('._access-menu [data-access-action="textToSpeech"]');
if (!tSpeechList) return;
```

Same goes for `speechToText(destroy: boolean)`, it should check if the element button exist before running:
```javascript
if (!document.querySelector('._access-menu [data-access-action="speechToText"]')) return;
```
We can also store the element as a `const` or a `let` so we don't need to access the DOM twice.

That's also a better approach in terms of encapsulation . . .

Let me know what you think.

**Comment by FedyukRimon** [comment]
@ranbuch Yes, it sounds better (I wanted to solve it that way too but I was unsure).
I pushed a change to the PR, If you want to add more changes, feel free to ask..

**Comment by ranbuch** [comment]
@FedyukRimon that's perfect, thanks for your contribution!
