### ISSUE TITLE
Persistence across pages

### ISSUE THREAD

**Issue by brianteeman** [ranbuch/accessibility#5]
Hi

I was looking to integrate this script with the next major release of Joomla https://github.com/joomla/joomla-cms/pull/24112#issuecomment-496163389 but unfortunately it seems that any change you make eg font size is lost as soon as you load the next page.

Am I missing something?

**Comment by brianteeman** [comment]
Anything?

**Comment by brianteeman** [comment]
@eldadflux - any ideas?

**Comment by ranbuch** [comment]
Hi @brianteeman, sorry for the late response.
I don't know if it's still relevant but one thing you can do is just override the `style` attribute you want change in your `css` like so:
```css
body ._access-menu ul li {
    font-size: 22px;
}
```
If you cant I guess I can find the time to add the icons font size to the options.

**Comment by ranbuch** [comment]
I have just realized that my replay doesn't really answer your question.

What you want is a session feature, I guess I can do that.

Just let me know if your request is still relevant.

**Comment by brianteeman** [comment]
yes that is correct. Without it the script is useless

**Comment by ranbuch** [comment]
I've upgrade the `npm` version to `3.0.1`.

This version contains more features by @SeFeX .

Let me know if that is what you need.

**Comment by brianteeman** [comment]
Thanks - the session thing works. Now I can work on the integration with Joomla.
