### ISSUE TITLE
Crashing React App

### ISSUE THREAD

**Issue by Elijer** [ranbuch/accessibility#51]
I'm following the instructions to use this package:
1. Download the package on npm (I've tried a couple of different versions)
2. Added this line to the top level of my Javascript code: `window.addEventListener('load', function() {
    new Accessibility();
}, false);`

It strangely did work for a moment but it is now crashing the website it is embedded in and I can't figure out why. Has an issue like this been discovered before? Does it resemble any prior difficulties anyone has bad with this package?

**Comment by FedyukRimon** [comment]
@Elijer I faced the same issue, and it was solved by adding to options:
```
session: {
    persistent: false,
},
```

**Comment by ranbuch** [comment]
Hi @Elijer and @FedyukRimon . Can we close this issue?

**Comment by FedyukRimon** [comment]
@Elijer for you to decide as the author of the issue :)
