### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined       

### ISSUE THREAD

**Issue by hmingv** [ranbuch/accessibility#53]
Hi I am using this tool in my Nuxt3 project.

But when I executed npm run dev, I encountered the following problem. I guessed it was because my dependency library version was too high, but I don't know which dependency it is. . . Could you please help me to have a look?

My dependencies are as follows:
![image](https://user-images.githubusercontent.com/57735185/225205683-acad1f57-a209-437e-80e7-d87f86befd97.png)

ReferenceError: regeneratorRuntime is not defined                                                                                                                                                               12:09:24  
    at D:\projects\develop\demo\node_modules\accessibility\dist\main.js:768:56
    at D:\projects\develop\demo\node_modules\accessibility\dist\main.js:871:6
    at Object.<anonymous> (D:\projects\develop\demo\node_modules\accessibility\dist\main.js:1540:2)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 500,
  fatal: false,
  unhandled: false,
  statusMessage: undefined,
  __nuxt_error: true
}

**Comment by hmingv** [comment]
![image](https://user-images.githubusercontent.com/57735185/225205811-a00d6a20-91df-4e31-8db0-15eae77db831.png)

Here are my previous dependencies, and accessibility works fine when using these dependencies.

**Comment by mtahirgulzar** [comment]
still  facing the same issue in next js

**Comment by ranbuch** [comment]
@hmingv I have no idea. Perhaps [this](https://dev.to/hulyakarakaya/how-to-fix-regeneratorruntime-is-not-defined-doj) could help?

**Comment by georgescubogdan** [comment]
I had the same issue on an older Angular app, fixed it by installing regenerator-runtime and adding the next lines to polyfils.ts
```
import "core-js/es6";
import "regenerator-runtime/runtime";
```

**Comment by noumanmoeen0** [comment]
> Having this issue in Next 13.4.19. I haven't found a workaround as yet, but will post if/when I do

Did you find any fix for this ?

**Comment by owain-williams** [comment]
> > Having this issue in Next 13.4.19. I haven't found a workaround as yet, but will post if/when I do
> 
> Did you find any fix for this ?

Sadly not. I mostly needed it for text-to-speech, and found a different package that fit my needs (speak-tts)

**Comment by ranbuch** [comment]
@hmingv @mtahirgulzar @georgescubogdan @owain-williams @noumanmoeen0 I believe I've fixed this issue on version `4.5.9`. Please give it a try if you still in search for an accessibility solution.

**Comment by hmingv** [comment]
Thank you very much for your continued attention to this Issue.

I'm excited to test the new version and bring you feedback.

Let me introduce you to my project environment:
Nuxt project info: 11:40:53

----------------------------------
- Operating System: Windows_NT
- Node Version: v20.1.0
-Nuxt Version: 3.10.3
- CLI Version: 3.10.1
- Nitro Version: 2.8.1
- Package Manager: pnpm@8.14.2
- Builder: -
- User Config: devtools, modules, typescript, eslint, runtimeConfig
- Runtime Modules: @pinia/nuxt@0.5.1, @nuxtjs/eslint-module@4.1.0, @nuxtjs/tailwindcss@6.11.4
- Build Modules: -
----------------------------------

I followed the documentation and here is what I did:
![image](https://github.com/ranbuch/accessibility/assets/57735185/9f6cfdf7-b0b7-4452-97a4-922babacb825)

![image](https://github.com/ranbuch/accessibility/assets/57735185/8085ac7f-a247-4109-80b7-03d906b5922d)

I got the following error:
![image](https://github.com/ranbuch/accessibility/assets/57735185/8e392ddf-27e1-4fdf-baf3-6617e490962f)

**Comment by hmingv** [comment]
[provide a minimal reproduction](https://codesandbox.io/p/devbox/serene-shamir-fmm99j?file=%2Fapp.vue%3A6%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltqtjdul00073j6geuues8e1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltqtjdul00023j6gqbyqvtwp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltqtjdul00043j6g33q0x0ug%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltqtjdul00063j6gpsfsalow%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltqtjdul00023j6gqbyqvtwp%2522%253A%257B%2522id%2522%253A%2522cltqtjdul00023j6gqbyqvtwp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltqto8z900023j6g52g4j249%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltqto8z900023j6g52g4j249%2522%257D%252C%2522cltqtjdul00063j6gpsfsalow%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltqtjdul00053j6ggs2oifob%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltqtjdul00063j6gpsfsalow%2522%252C%2522activeTabId%2522%253A%2522cltqtjdul00053j6ggs2oifob%2522%257D%252C%2522cltqtjdul00043j6g33q0x0ug%2522%253A%257B%2522id%2522%253A%2522cltqtjdul00043j6g33q0x0ug%2522%252C%2522activeTabId%2522%253A%2522cltqtjdul00033j6gq7sikko5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltqtjdul00033j6gq7sikko5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520update%2522%252C%2522id%2522%253A%2522cltqtr6oa00hv3j6go1vtc7p6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ranbuch** [comment]
Thank you for the effort @hmingv!
unfortunately the provided link to [codesandbox.io](https://codesandbox.io) doesn't work for me. Perhaps it's private (I'm not familiar with `codesandbox`)?

Please try to install version `4.5.10` end let me know how it goes.

**Comment by hmingv** [comment]
Oh, sorry, I shared the private link by mistake, the following link is public link

https://codesandbox.io/p/devbox/serene-shamir-fmm99j?file=%2Fapp.vue%3A6%2C1

**Comment by hmingv** [comment]
Version 4.5.10 got new error message:

![image](https://github.com/ranbuch/accessibility/assets/57735185/7bd08ed3-9786-4e07-a587-f81564cd7b35)

When I set the page to client rendering, I got the following error:

![image](https://github.com/ranbuch/accessibility/assets/57735185/46044831-3efe-4b0d-ab77-bf7f9c2f3308)

**Comment by ranbuch** [comment]
@hmingv I was able to access and run the `codesandbox` app. I believe I have [forked it](https://codesandbox.io/p/devbox/angry-glitter-mrp44l?file=%2Fapp.vue%3A14%2C8-16%2C8) and made a few changes.

1. Updated to version `4.5.11`.
2. Made sure the older version is not cached by editing the `nuxt.config` file by adding this section:
```javascript
vite: {
    optimizeDeps: {
      exclude: [
        'date-fns'
      ]
    }
}
```
3. Edited the `app.vue` by removing the `window.addEventListener` as the `onMounted` event is being triggered after the window has already loaded (so just call `new Accessibility();` immediately).

**Comment by hmingv** [comment]
Thanks for fixing this, it looks good now.

It’s just that this dependency uses window, so it does not support SSR. I added a new Nuxt Plugin to load it on the client, and it can be used normally now. Thank you.

https://codesandbox.io/p/devbox/serene-shamir-fmm99j?file=%2Fapp.vue%3A6%2C1
