### ISSUE TITLE
font not increase.

### ISSUE THREAD

**Issue by RoniJackVituli** [ranbuch/accessibility#54]
i used react and design with css
why when i wrote for element a class with font-size , and then i try to increase is not change... 
for example 
.title{
 font-size:20px;
}
and when i try to increase or decrease is not change.. but if delete the font-size is change.
how i can make it that it will change any time?

**Comment by ranbuch** [comment]
Hi @RoniJackVituli 
As written on the documentation, you can set the `textPixelMode` option to true like this:
```javascript
new Accessibility({ textPixelMode: true })
```
