### ISSUE TITLE
Close/Reset buttons wont work

### ISSUE THREAD

**Issue by IamShaharFar** [ranbuch/accessibility#58]
if i'm opening the accesability menu i cant close it untill i refresh the page and the reset button wont reset the style to the basic one.

**Comment by ranbuch** [comment]
Hi @IamShaharFar can you please provide a link where I could reproduce the issue?

**Comment by IamShaharFar** [comment]
when i open the accessibility menu i cant close it with the x (close button) and also can't reset to default while using with browser

**Comment by idesthic** [comment]
@IamShaharFar if you're using React, try removing the <React.StrictMode> tag
