### ISSUE TITLE
button order

### ISSUE THREAD

**Issue by brianteeman** [ranbuch/accessibility#62]
How can I control the order that the buttons are displayed in. Specifically I want to place the CUSTOM IFRAME at the bottom of the list. Currently it appears between big cursor and reading guide and it would make more sense to me at the top or bottom of the list

**Comment by ranbuch** [comment]
Hi @brianteeman,

I think we could kill two birds with one stone [(related issue)](https://github.com/ranbuch/accessibility/issues/63). We can expose the `order` CSS attribute as a variable to each option. That way the developer would be able to determine the desired order.

WDYT?

**Comment by brianteeman** [comment]
my understanding is that using "order" is not a good approach for accessibility https://developer.mozilla.org/en-US/docs/Web/CSS/order#accessibility_concerns

tbh my only real desire here is to place the custom iframe at the bottom of the list

**Comment by ranbuch** [comment]
@brianteeman I see your point. we'll add a new option to sort the modules.

**Comment by brianteeman** [comment]
thanks

**Comment by brianteeman** [comment]
Closing as fixed in 5.0.0
