### ISSUE TITLE
demo site errors

### ISSUE THREAD

**Issue by brianteeman** [ranbuch/accessibility#73]
See screenshots

Chrome 125 on windows 11

![image](https://github.com/ranbuch/accessibility/assets/1296369/fefc7025-0e3b-41fc-89b7-7e7ee4aae73d)

Chrome 126 on osx
![image](https://github.com/ranbuch/accessibility/assets/1296369/3ff8a5e5-4223-44a2-8043-09cd544a88b7)

**Comment by ranbuch** [comment]
Fixed, thank you @brianteeman
