### ISSUE TITLE
how to use with angular 

### ISSUE THREAD

**Issue by AhmedHossamFCI** [ranbuch/accessibility#78]
just i am wondering how to use this lib with angular 18?

**Comment by ranbuch** [comment]
Hi @AhmedHossamFCI 
You can use it just like you would with any other type of library, framework of vanilla javascript. I've actually tried it on some simple testing Angular app and it works as expected.

1. Add the package to the `dependencies` section on the `package.json` file:
```javascript
"accessibility": "*"
```
and run `npm install`.
2. Import the `Accessibility` class to the component that you want to display the tool (for example `app.component.ts`) like so:
```javascript
import { Accessibility } from 'accessibility';
```
3. Create a new instance of the class like this:
```javascript
ngAfterViewInit() {
  setTimeout(async () => {
    new Accessibility();
  });
}
```


Please let me know if there are any issues with the tool in Angular.
