### ISSUE TITLE
How to change the size of the float icon

### ISSUE THREAD

**Issue by Berdugo1994** [ranbuch/accessibility#79]
I would like to change the size of the icon.
I can see that there was an option that deleted:
https://github.com/ranbuch/accessibility/commit/f6f48b97959d076d535622df1996caba62371c33#r147629569

Obviously I saw that I can change the:
```
  /* --_access-icon-width: 30px;
  --_access-icon-height: 30px; */
```
But, can't change the "person" inside the icon
<img width="65" alt="image" src="https://github.com/user-attachments/assets/e9da0503-ab5a-4353-8dff-5c05a8523cd6">

**Comment by ranbuch** [comment]
Hi @Berdugo1994 
Indeed you can alter the `--_access-icon-width` and `--_access-icon-height` CSS variables but you can also change the `--_access-icon-font` which has the default value of `40px / 45px "Material Icons"`, which means 
```css
font-size: 40px;
```
and
```css
line-height: 45px;
```

For example, you can try this CSS:
```css
:root {
    --_access-icon-width: 100px;
    --_access-icon-height: 100px;
    --_access-icon-font: 80px / 90px "Material Icons";
}
```
